Adicionada PHP do 0 - Orientação a Objeto
conferencias-dev/conferencias-dev pull request #117
Opened 2019-10-22 22:06 UTC by thiagobfiorenza

Issue #90

2019-10-22 22:12 UTC, Paulophmp approved these changes
OK

2019-10-23 18:00 UTC, Arkanius requested changes

2019-10-23 18:00 UTC, Arkanius commented on _posts/2019-11-09-php-do-0-2019.md
> +- mulheres
Por favor, remover essa tag, como é a primeira vez que ela aparece acredito que não precisamos mantê-la no projeto

2019-10-23 18:00 UTC, Arkanius commented
@thiagobfiorenza muito obrigado pela sua contribuição! Deixei apenas um comentário para ser corrigido, após isso, poderemos mergear a sua pr :)

2019-10-23 18:38 UTC, Arkanius approved these changes

2019-10-23 18:38 UTC, merged

2019-10-23 18:38 UTC, Arkanius commented
@thiagobfiorenza obrigado pela contribuição! Acompanhe o nosso twitter para ver a nossa divulgação https://twitter.com/conferenciasdev

:)