Adding new event
conferencias-dev/conferencias-dev pull request #132
Opened 2019-11-11 17:57 UTC by edgarberlinck

Adding new event

2019-11-11 18:52 UTC, Arkanius requested changes
Muito obrigado pela contribuição! Precisamos apenas fazer alguns ajustes para disponibilizar a sua conferência no nosso espaço! 

Seguem as revisões necessárias

2019-11-11 18:52 UTC, Arkanius commented on _posts/2019-12-04-machine-learning-e-ux-2019.md
> +- Machine Learning
por favor, usar a tag: *machine-learning* e normalizar a tag UX para *ux*

2019-11-11 18:52 UTC, Arkanius commented on _posts/2019-12-04-machine-learning-e-ux-2019.md
> +description: 'O futuro onde as máquinas podem pensar e falar como nós humanos está cada vez mais presente. Logo, é importante explorar algumas das propriedades técnicas e restrições de sistemas de ap
Essa descrição esta boa, porém, neste ponto ela precisa ser um pouco mais curta para facilitar o posicionamento na página e as nossas publicações. Pode dar uma resumida seguindo o exemplo a seguir?

![image](https://user-images.githubusercontent.com/6404401/68612249-d7c97400-049a-11ea-8a40-be562db61903.png)

2019-11-11 18:52 UTC, Arkanius commented on _posts/2019-12-04-machine-learning-e-ux-2019.md
> +
Precisamos fechar a tag do markdown para que o layout não quebre no pré processamento :). Por favor, adicione: 
```
---
```

2019-11-12 15:33 UTC, Arkanius requested changes

2019-11-12 15:33 UTC, Arkanius commented on _posts/2019-12-04-machine-learning-e-ux-2019.md
> +
Precisamos de apenas uma correção, este é o lugar em que deve ser inserido o: 
```
---
```

2019-11-12 15:33 UTC, Arkanius commented on _posts/2019-12-04-machine-learning-e-ux-2019.md
> +---
Este **---** pode ser removido daqui e substituído pelo comentário acima

2019-11-12 16:43 UTC, edgarberlinck commented on _posts/2019-12-04-machine-learning-e-ux-2019.md
> +
Putz. Beleza, corrigido

2019-11-12 16:54 UTC, Arkanius commented
Obrigado pela contribuição @edgarberlinck :)

Siga o nosso [twitter](https://twitter.com/conferenciasdev) para acompanhar a divulgação do seu evento!

2019-11-12 16:54 UTC, Arkanius approved these changes

2019-11-12 16:54 UTC, merged